### ISSUE TITLE
It is time for a new release

### ISSUE THREAD

**Issue by satorumpen** [fastify/create-fastify#48]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

fastify-cli that create-fastify refers to is outdated and the new options for `fastify eject` were not available.

**Comment by Eomm** [comment]
Definitely!

Released new version: https://github.com/fastify/create-fastify/releases/tag/v4.0.0

Thanks for pointing out 👍🏼

**Comment by satorumpen** [comment]
Thanks for the quick release!
